config/routes.rb
Rails.application.routes.draw do
 
 resource :contents
 root 'results#search'
 get '/contents'=>'contents#index'
 post '/contents'=>'contents#create'
 get '/contents/new'=>'contents#new'
 get '/contents/delete/:id'=>'contents#delete' , as: :delete_path
 get '/contents/search'=>'results#search'
 get 'contents/show/:id'=>'contents#show' ,as: :show
 get '/contents/edit/:id'=>'contents#edit' ,as: :edit
 #get '/contents/update'
 #patch '/contents/update'

end

app/models/content.rb
require 'elasticsearch/model'
class Content < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  if !Content.__elasticsearch__.index_exists?

  	Content.__elasticsearch__.create_index! force: true
  end

end
Content.import

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def new
  	@msg=Content.new
  end

  def index
  	@msgs=Content.all
  end

  def create
   @msg=Content.new(msg_params)
   if !@msg.save
   	render 'new'
   end
  end

  def delete
  	@msg=Content.find(params[:id])
  	@msg.destroy()
  	redirect_to '/contents'
  end
   
def update
  @msg=Content.find(params[:id])
  if @msg.update(update_params)
    redirect_to controller: 'contents', action: 'show', id: @msg
  else
    render 'edit'
  end
end
    
    def edit
      @msg=Content.find(params[:id])
    end

  def show
  	@result=Content.find(params[:id])
  end
  private 

  def msg_params
  	params.require(:content).permit(:data,:owner)
  end

  def update_params
  	params.require(:content).permit(:data,:owner)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController


	def search
		if params[:q].nil? || params[:q]==''
        @results=[]
       else
       @results = Content.search params[:q]
       if @results.count==0
       	   @text='No Results'
       	else
       		@text='Your Results Are'
       end
        end
	end



end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
		if params[:q].nil?
    @results = []
  else
    @results = Content.search params[:q]
  end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/contents/create.html.erb
<p align='center'>Message created Successfully 
<%= link_to 'Home', controller: "results", action: "search"%></p>

app/views/contents/edit.html.erb
<%=form_for @msg , :url=>{:action=>"update" ,:id=> @msg} do |f| %>
<div align="center">
    <p><%= f.label :Owner%><br>
	<%= f.text_field :owner %><br></p>
	<p><%= f.label :Data%><br>
    <%= f.text_field :data%><br>
    <%= f.submit 'update'  %></p>
</div>
<%end%>

app/views/contents/home.html.erb
<h1>Search</h1>

<%= form_for 'contents/search', method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

app/views/contents/index.html.erb
<% @msgs.each do |m|%>
<p align="center"><%= m.data%> By <%= m.owner%> <%= link_to 'Delete' , delete_path_path(m) %>  </p>
<%end%>
<p align='center'><%= link_to 'New Message' ,'contents/new' %></p>

app/views/contents/new.html.erb
<%=form_for(@msg) do |f| %>
<div align="center">
    <p><%= f.label :Owner%><br>
	<%= f.text_field :owner %><br></p>
	<p><%= f.label :Data%><br>
    <%= f.text_field :data%><br>
    <%= f.submit 'GoCreate' %></p>

</div>
<%end%>

app/views/contents/show.html.erb
<p align='center'><%= @result.data%> By <%= @result.owner%>
<%= link_to 'Home', controller: "results", action: "search"%>
<%= link_to 'Edit',edit_path(@result)%> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Message</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/search.html.erb
<h1 align="center">Search Your Content</h1>
<p align="right"><%= link_to 'Create Record', controller: "contents", action: "new"%></p>
<%= form_for 'contents/search' ,:class=>'field',method: :get do |f| %>
  <p align='center'>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  
<% end %>
 </p>
 <p><%= @text%></p>
 <%if @text.nil? %>
 <p>No Results</p>
 <%end%>
<ul align='center'>
  <% @results.each do |result| %>
   <table>
   <th>
   <tr>
       <%= link_to result.data, controller: "contents", action: "show", id: result._id%>
    </tr>
    </th>
  </table>
  <% end %>
</ul>

app/views/search/search.html.erb
<% @results.each do |r| %>
<p><%= r.data %> By <%= r.owner %></p>
<%end%>